### ISSUE TITLE
Проблемы с переводом версии 4.0.2

### ISSUE THREAD

**Issue by mdvadim** [smeagol74/archi-ru#1]
В версии Archi 4.0.2 не перевелись названия связей во всплывающем меню. Где-то ещё видел, но сейчас не нахожу. С программой работают сами врачи-руководители. Будем признательны, если восстановите объем переведённого.
![default](https://user-images.githubusercontent.com/29094130/28662554-c45b919a-72e4-11e7-85d1-651185df6c8d.png)

**Comment by smeagol74** [comment]
Адаптировал перевод для версии [4.0.2](https://github.com/smeagol74/archi-ru/releases/tag/4.0.2.201707292013).

**Comment by mdvadim** [comment]
Здравствуйте, Константин!
Может быть, в архиве не те файлы? Не перевелись не только всплывающие меню, но и строка меню. Я даже снёс Archi, подумал, что старый перевод конфликтует. 
![default](https://user-images.githubusercontent.com/29094130/28761779-587f7bea-75db-11e7-8aca-17eb3fac8daf.png)
Во-вторых, в инструкции написано "...распаковать файлы из папки plugins вашего архива...", но в вашем архиве папка имеет другое название: archi-ru-master.

Строки выводятся корректно.
![default](https://user-images.githubusercontent.com/29094130/28761939-ba1e465a-75dc-11e7-87fb-ae5dba66e0aa.png)

**Comment by smeagol74** [comment]
Вы точно вот этот вот архив скачали: https://github.com/smeagol74/archi-ru/releases/download/4.0.2.201707292013/archi-ru.4.0.2.201707292013.zip а не архив с исходниками (Sources)?

Я только что русифицировал свежую версию на работе из этого релиза и с ним всё в порядке.

**Comment by mdvadim** [comment]
Конечно, Константин!
Вот действия и сам архив во вложении.

![default](https://user-images.githubusercontent.com/29094130/28762751-2fc95a56-75e3-11e7-9ea2-a2b4d02f8b4d.png)




![default](https://user-images.githubusercontent.com/29094130/28762749-279f3378-75e3-11e7-8132-c729aeb0fce9.png)
[archi-ru-master.zip](https://github.com/smeagol74/archi-ru/files/1186406/archi-ru-master.zip)

**Comment by smeagol74** [comment]
:) Вы мне пишете "Конечно", и тут же демонстрируете, как вместо того, чтобы скачать скомпилированный архив из релиза (как, кстати, написано в инструкции), скачиваете архив текущей версии исходников, которые нельзя просто так установить в рабочую систему, а нужно предварительно компилировать.

Вам нужно пройти на закладку "releases" и оттуда качать собранную версию.

Действуйте по инструкции, там на "архив с переводом" подвешена ссылочка на выпущенные релизы, и будет вам счастье.

**Comment by smeagol74** [comment]
Подправил инструкцию, так должно быть меньше непоняток.

**Comment by mdvadim** [comment]
:-) Ну кто бы подумал, что не надо нажимать на **яркую** БОЛЬШУЮ кнопку DOWNLOAD??!!
Первый раз действовал по инструкции, вспомнил. А сейчас - уже привык к интерфейсу github и, конечно, что мне, читать инструкции?! :-) 
Извините. Еще раз, большое спасибо.
