### ISSUE TITLE
Проблема: лимит на отображение количества букв в строках отчётов в русской версии

### ISSUE THREAD

**Issue by mdvadim** [smeagol74/archi-ru#2]
Здравствуйте smeagol74! 
Во такая проблема есть, как выясняется, именно в русском Archi. Phil Beauvoir исправил эту проблему, но, как выясняется, в русской версии она осталась.
Ссылка по вопросу: https://github.com/archimatetool/archi/issues/242. 

Я эту проблему Филу описал тоже. Но, думаю, он оставит решение этой проблемы за русской стороной. Сможете исправить и это?

Hi dear Phil,
I so sorry I was out of my office. 
Problem restored for all type of elements in case Russian add. 
For example:
Native Archi:
![default](https://user-images.githubusercontent.com/29094130/28713065-cf442f80-73b7-11e7-9b7f-048ce01874c0.png)
Modify Archi:

![default](https://user-images.githubusercontent.com/29094130/28713166-383961cc-73b8-11e7-8309-569f23001c16.png)

![default](https://user-images.githubusercontent.com/29094130/28713175-40176876-73b8-11e7-8867-7dadaa0ef7bc.png)

**Comment by smeagol74** [comment]
Адаптировал перевод для версии [4.0.2](https://github.com/smeagol74/archi-ru/releases/tag/4.0.2.201707292013). Выгрузил Jasper отчёт, вроде появились длинные строчки и в русском варианте.

**Comment by mdvadim** [comment]
Большое спасибо, можно по имени?, Константин!

**Comment by smeagol74** [comment]
Пожалуйста. Конечно можно.
