### ISSUE TITLE
Дата на титульном листе

### ISSUE THREAD

**Issue by mdvadim** [smeagol74/archi-ru#3]
Ещё раз, здравствуйте Константин!
На титульном листе отчётов в русском варианте некорректно отображается дата. Фил дал мне совет, я повторяю это в ручную после каждого обновления, равно как и подгрузку русских файлов. 

Не знаю почему, но корректно отображается только короткий месяц d.mm.yyyy, поэтому я правлю исходный формат на d.MM.YY. Длинный АВГУСТ, или как в исходнике АВГ не отображается вообще. 

Можно это включить в русификацию как-то? Это не сложно повторять, но наверное все правят в ручную, или не правят.

_Ниже, копия переписки с Филом.
В самом начале я начал контактировать с Филом через сайт archimate, не знал ещё о github, поэтому этого нет здесь, только у меня на почте:_
____________________________________________________________________________________________________________
Hi Vadim,

this is strange. I tested it and it seems OK:

 
![default](https://user-images.githubusercontent.com/29094130/28763273-eea08190-75e6-11e7-9490-7d4f43d05b05.png)

I wonder if this is because it is in Russian?

There is a file "main.jrxml", in the Archi plugins folder, and in folder com.archimatetool.jasperreports/reports/Customizable Report,  with this code in it:

    <parameter name="DATE_NOW" class="java.lang.String">
        <defaultValueExpression><![CDATA[(new java.text.SimpleDateFormat("d MMM yyyy HH:mm:ss")).format(new java.util.Date())]]></defaultValueExpression>
    </parameter>

Perhaps you could experiment with this?

Regards,

Phil
On 15/03/2017 13:21, Вадим Германович Харкевич wrote:
Dear support,
First page of report contains just DD and YYYY made and Archi 3.0 and Archi 4.0.
 
![default](https://user-images.githubusercontent.com/29094130/28763289-0fc81946-75e7-11e7-99c0-2644491978f3.png)
  
 
Regards,
Dr. Vadim Harkevich, M.D.
 

-- 
Phil Beauvoir
Archi | ArchiMate Modelling
http://www.archimatetool.com

**Comment by mdvadim** [comment]
Сам понял, что нужно не менять в ручную каждый раз, а в вашем архиве сделать изменения и сохранить.
plugins\com.archimatetool.jasperreports.ru_4.0.2.201707292013\nl\ru\reports\Customizable Report\main.jrxml.

**Comment by smeagol74** [comment]
Лучше даже сделать не так, а ещё "продвинутей".

Архи позволяет создавать собственные шаблоны для отчётов Jasper, в настройках "Редактировать → Preferences → Отчёты Jasper" можно задать каталог в котором эти шаблоны хранятся. Надо скачать самую свежую версию исходников для отчёта, например из моего хранилища: https://github.com/smeagol74/archi-ru/tree/master/com.archimatetool.jasperreports.ru/nl/ru/reports/Customizable%20Report и всю эту папочку `Customizable Report` сохранить в каталоге, который в настройках указали. Переименовать его как-нибудь, как вам нравится. Внести в него любые нужные вам изменения, формат даты, может картинку фоновую другую поставить, какая вам нужна, колонтитулы "фирменные" может ещё чего и в дальнейшем пользоваться не поставляемым с Архи шаблоном отчёта "Customizable Report", а вашим собственным настроенным на ваши нужды и потребности (он должен появиться в списке при выборе шаблона для отчёта).

Кстати редактировать шаблоны отчёта не обязательно вручную, есть графические редакторы их можно на страничке в [википедии](https://ru.wikipedia.org/wiki/JasperReports#.D0.93.D1.80.D0.B0.D1.84.D0.B8.D1.87.D0.B5.D1.81.D0.BA.D0.B8.D0.B5_.D0.B4.D0.B8.D0.B7.D0.B0.D0.B9.D0.BD.D0.B5.D1.80.D1.8B_.D0.B4.D0.BB.D1.8F_JasperReports) поглядеть.

Мне кажется, так будет правильнее. Странно, что Фил вам такой вариант не предложил.

С этой датой вообще странное дело, если честно. Похоже буковки пропадают только при выгрузке в PDF. В HTML версии и ODT всё в порядке с месяцем. Видимо чего-то со шрифтами.

**Comment by smeagol74** [comment]
Точно в шрифте дело. Добавил в этот элемент другой шрифт (Dejavu Sans) и тут же вышел месяц из тумана, как в считалочке поётся.

Это в файле `main.jrxml` надо добавить `textElement/font`, если вам вдруг больше с буковками дата нравится.

```xml
<textField pattern="">
    <reportElement positionType="Float" x="1" y="349" width="515" height="20" uuid="0d3ecbc2-8dbe-4a48-a461-34c06224f5a4"/>
    <textElement>
        <font fontName="DejaVu Sans"/>
    </textElement>
    <textFieldExpression><![CDATA[$P{DATE_NOW}]]></textFieldExpression>
</textField>
```

**Comment by smeagol74** [comment]
Нарисовал [pull-request](https://github.com/archimatetool/archi/pull/262) в основную ветку Archi, который устанавливает дате "правильный" стиль.

**Comment by smeagol74** [comment]
Я удалил из русификации шаблоны Jasper отчётов, нечего там русифицировать по сути оказалось. Мой патч, исправляющий проблему со шрифтом, Фил уже включил в основную ветку кода, так что лучше взять за основу для своих модификаций ту основную версию отчёта: https://github.com/archimatetool/archi/tree/master/com.archimatetool.jasperreports/reports/Customizable%20Report, а не ту ссылку, что я давал ранее.

**Comment by smeagol74** [comment]
Считаю, что проблема решена. С выходом свежих версий Archi русские даты будут работать в PDF из коробки.
