### ISSUE TITLE
4.0.3

### ISSUE THREAD

**Issue by mdvadim** [smeagol74/archi-ru#4]
Здравствуйте Константин!
Не требуется к версии Archi 4.0.3., с учетом изменений внесённых в Archimate 3.01, изменить и перевод на русский?

**Comment by smeagol74** [comment]
Понятия не имею. А что, чего-то непереведённое новое появилось, или в связи с этими изменениями потеряло актуальность? С вашей стороны будет конструктивнее писать, что вы обнаружили чего-то непереведённое или требуещее корректив, чем такие риторические вопросы. Если уж вы не имеете возможностей сделать форк, внести требуемые изменения и вернуть их через pull-request.

**Comment by mdvadim** [comment]
Ок, Я учту замечание.

**Comment by mdvadim** [comment]
Связи остались прежними, изменились их правила.
