### ISSUE TITLE
Арки обрезает длинные строки заголовков.

### ISSUE THREAD

**Issue by mdvadim** [smeagol74/archi-ru#5]
Здравствуйте Константин!
Открыл новую тему с @Phillipus. Арки обрезает длинные строки заголовков. https://github.com/archimatetool/archi/issues/325
Он исправил, создав сегодня 4.1.1.beta. Я поставил её, как всегда, тут же русифицировал. Ошибка сохранилась. 

В ходе обсуждения выяснилось, что в английской версии на самом деле всё исправилось. А как только в русскую - возвращается. Все скриншоты в ветке есть.
Посмотрите, пожалуйста. Спасибо заранее.

**Comment by smeagol74** [comment]
Спасибо за информацию. Я постараюсь поглядеть на ближайшей неделе.

**Comment by mdvadim** [comment]
Приветствую Константин!
Не находится время исправить баг?

**Comment by smeagol74** [comment]
Попробуйте удалить каталог `${ARCHI-DIR}/plugins/com.archimatetool.jasperreports.ru_4.0.2.201707292013/nl` и перезапустить Archi.

**Comment by mdvadim** [comment]
![default](https://user-images.githubusercontent.com/29094130/36273974-de36af04-12b8-11e8-8124-1692652bf891.png)
Вроде всё ОК. На домашней машине. Проверю завтра и на работе . Весрия Archi 4.2. Русификатор 4.02.
Спасибо!
P.S. В Кемеровском кардиоцентре теперь у вас есть друзья. Обращайтесь.

**Comment by mdvadim** [comment]
Спасибо Константин. Всё работает.

**Comment by mdvadim** [comment]
Спасибо Константин. Всё работает.
