### ISSUE TITLE
Актуальность инструкции

### ISSUE THREAD

**Issue by WatchTh1** [smeagol74/archi-ru#6]
Доброго! В инструкции по переводу есть несколько ошибок. В т.ч. про "перевод базовых компонентов Eclipse" (по имеющейсяссылке - file not found 404). Сейчас заканчиваю перевод на русский для версии 4.3.1, остались подсказки и базовые компоненты. 
Если подскажете - буду весьма благодарен.

**Comment by smeagol74** [comment]
Спасибо, исправил ссылку в инструкции на перевод базовых компонентов Eclipse Oxygen
